// بنك الأسئلة: ضيف أسئلة جديدة في آخر القايمة بنفس الشكل (متحطش أسئلة في النص علشان ترتيب الأسئلة اللي اتلعبت ما يتلخبطش)
// [الجملة الإنجليزي, الترجمة, [الاختيارات], رقم الإجابة الصح (يبدأ من 0), الملاحظة, النوع v/g/w, المرحلة m=إعدادي p=ابتدائي]
var Q=[
["It is very ____ today, so I need my coat.", "الجو برد جدًا النهاردة، فمحتاج جاكتي.", ["cold", "hot", "sunny", "dry"], 0, "الجاكت بنلبسه في البرد", "v", "m"],
["He is very ____ . He saved the cat.", "هو شجاع جدًا. هو أنقذ القطة.", ["Brave", "Lazy", "Hungry", "Quiet"], 0, "Brave = شجاع", "v", "m"],
["I am ____ because I did not eat all day.", "أنا جعان لأني ماكلتش طول اليوم.", ["Angry", "Hungry", "Late", "Cold"], 1, "Hungry = جعان", "v", "m"],
["We use a ____ to write on paper.", "بنستخدم قلم علشان نكتب على الورق.", ["pen", "chair", "door", "bus"], 0, "pen = قلم", "v", "m"],
["My mother works in a hospital. She is a ____ .", "أمي بتشتغل في مستشفى. هي ممرضة.", ["farmer", "nurse", "pilot", "baker"], 1, "nurse = ممرضة", "v", "m"],
["The opposite of big is ____ .", "عكس كبير هو صغير.", ["tall", "long", "small", "fast"], 2, "small = صغير", "v", "m"],
["I wash my hands with ____ and water.", "بغسل إيديا بالصابون والمية.", ["soap", "bread", "paper", "milk"], 0, "soap = صابون", "v", "m"],
["A place where we borrow books is a ____ .", "المكان اللي بنستلف منه كتب هو مكتبة.", ["shop", "library", "farm", "bank"], 1, "library = مكتبة", "v", "m"],
["She ____ to school every day.", "هي بتروح المدرسة كل يوم.", ["go", "goes", "going", "gone"], 1, "مع he/she/it بنزوّد s للفعل", "g", "m"],
["They ____ playing football now.", "هم بيلعبوا كورة دلوقتي.", ["is", "am", "are", "be"], 2, "مع they بنستخدم are", "g", "m"],
["I ____ breakfast yesterday at 8.", "أنا فطرت امبارح الساعة 8.", ["eat", "eats", "ate", "eaten"], 2, "yesterday = ماضي، وماضي eat هو ate", "g", "m"],
["There ____ two books on the desk.", "في كتابين على المكتب.", ["is", "are", "am", "be"], 1, "كتابين = جمع، يبقى are", "g", "m"],
["He does not ____ milk.", "هو مش بيحب اللبن.", ["likes", "like", "liking", "liked"], 1, "بعد does not بنكتب الفعل من غير s", "g", "m"],
["My sister is ____ than me.", "أختي أطول مني.", ["tall", "taller", "tallest", "more tall"], 1, "المقارنة: كلمة قصيرة + er", "g", "m"],
["We ____ to the park tomorrow.", "إحنا هنروح الحديقة بكرة.", ["went", "goes", "will go", "going"], 2, "tomorrow = مستقبل، نستخدم will", "g", "m"],
["This is ____ apple.", "دي تفاحة.", ["a", "an", "some", "many"], 1, "apple بتبدأ بحرف متحرك، يبقى an", "g", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She likes pizza.", "He go to school.", "They are happy.", "I am a student."], 1, "الصح: He goes to school", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["My father work in a bank.", "She is my friend.", "I like tea.", "They live here."], 0, "الصح: My father works in a bank", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["There is a book.", "She don't like fish.", "We are late.", "It is cold."], 1, "الصح: She doesn't like fish", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I can swim.", "He can swims fast.", "She can run.", "They can sing."], 1, "بعد can بنكتب الفعل من غير s", "w", "m"],
["It is raining, so I take my ____ .", "الدنيا بتمطر، فباخد الشمسية بتاعتي.", ["pillow", "sandwich", "umbrella", "guitar"], 2, "umbrella = شمسية", "v", "m"],
["My father drives a ____ to work.", "أبويا بيسوق عربية للشغل.", ["tree", "cloud", "spoon", "car"], 3, "car = عربية", "v", "m"],
["I drink ____ when I am thirsty.", "بشرب مية لما أبقى عطشان.", ["sand", "water", "chalk", "paper"], 1, "thirsty = عطشان", "v", "m"],
["Summer is very ____ in Egypt.", "الصيف حر جدًا في مصر.", ["icy", "freezing", "snowy", "hot"], 3, "hot = حار", "v", "m"],
["A ____ is a person who teaches students.", "المدرّس هو الشخص اللي بيعلّم الطلاب.", ["driver", "doctor", "teacher", "singer"], 2, "teacher = مدرّس", "v", "m"],
["She is ____ because she lost her toy.", "هي حزينة لأنها ضيّعت لعبتها.", ["proud", "excited", "sad", "happy"], 2, "sad = حزين", "v", "m"],
["We sleep at night in our ____ .", "بننام بالليل في أوضة النوم.", ["garage", "balcony", "bedroom", "bathroom"], 2, "bedroom = أوضة نوم", "v", "m"],
["The ____ gives us light and heat.", "الشمس بتدينا نور وحرارة.", ["snow", "sun", "wind", "rain"], 1, "sun = شمس", "v", "m"],
["I am ____ ; I want to sleep.", "أنا تعبان؛ عايز أنام.", ["busy", "funny", "tired", "early"], 2, "tired = تعبان", "v", "m"],
["A ____ lives in the sea.", "السمكة بتعيش في البحر.", ["horse", "bird", "cat", "fish"], 3, "fish = سمكة", "v", "m"],
["The opposite of easy is ____ .", "عكس سهل هو صعب.", ["clean", "simple", "hard", "soft"], 2, "hard = صعب", "v", "m"],
["My birthday is in ____ ; it is the first month.", "عيد ميلادي في يناير؛ هو أول شهر.", ["May", "March", "July", "January"], 3, "January = يناير", "v", "m"],
["You can buy bread at a ____ .", "تقدر تشتري عيش من المخبز.", ["school", "bakery", "library", "hospital"], 1, "bakery = مخبز", "v", "m"],
["I brush my ____ every morning.", "بغسل أسناني كل صباح.", ["hands", "books", "teeth", "shoes"], 2, "teeth = أسنان", "v", "m"],
["My brother ____ football every Friday.", "أخويا بيلعب كورة كل جمعة.", ["plays", "played", "playing", "play"], 0, "مع he/she/it بنزوّد s للفعل", "g", "m"],
["We ____ a test yesterday.", "كان عندنا اختبار امبارح.", ["have", "has", "had", "having"], 2, "yesterday = ماضي، وماضي have هو had", "g", "m"],
["She is ____ a book now.", "هي بتقرا كتاب دلوقتي.", ["read", "readed", "reads", "reading"], 3, "now = مضارع مستمر: is + ing", "g", "m"],
["I have ____ brothers and one sister.", "عندي أخين وأخت واحدة.", ["much", "two", "a", "an"], 1, "brothers = جمع، نستخدم رقم", "g", "m"],
["How ____ apples are in the basket?", "كام تفاحة في السلة؟", ["a", "much", "any", "many"], 3, "apples بتتعد، يبقى many", "g", "m"],
["How ____ milk do you drink?", "بتشرب لبن قد إيه؟", ["two", "much", "few", "many"], 1, "milk مش بيتعد، يبقى much", "g", "m"],
["He ____ his homework yesterday.", "هو عمل واجبه امبارح.", ["do", "did", "does", "doing"], 1, "yesterday = ماضي، وماضي do هو did", "g", "m"],
["Ahmed and Sara ____ my friends.", "أحمد وسارة أصحابي.", ["am", "is", "be", "are"], 3, "اتنين = are", "g", "m"],
["I get up ____ 7 o'clock.", "بصحى الساعة 7.", ["of", "at", "on", "in"], 1, "قبل الساعة بنستخدم at", "g", "m"],
["My birthday is ____ May.", "عيد ميلادي في مايو.", ["in", "at", "to", "on"], 0, "قبل الشهر بنستخدم in", "g", "m"],
["This book is ____ than that one.", "الكتاب ده أمتع من اللي ده.", ["most interesting", "interesting", "more interesting", "interestinger"], 2, "الكلمة الطويلة: more + الصفة", "g", "m"],
["They ____ at home last night.", "هم كانوا في البيت الليلة اللي فاتت.", ["were", "are", "was", "is"], 0, "they + الماضي = were", "g", "m"],
["I ____ my friend tomorrow.", "هقابل صاحبي بكرة.", ["will meet", "met", "meeting", "meets"], 0, "tomorrow = مستقبل: will + فعل", "g", "m"],
["She can ____ English very well.", "هي تقدر تتكلم إنجليزي كويس جدًا.", ["speaks", "speak", "speaking", "spoke"], 1, "بعد can بنكتب الفعل من غير s", "g", "m"],
["____ you like pizza?", "بتحب البيتزا؟", ["Is", "Does", "Are", "Do"], 3, "مع you بنستخدم Do", "g", "m"],
["My mother ____ cook every day.", "أمي مش بتطبخ كل يوم.", ["doesn't", "don't", "isn't", "aren't"], 0, "مع she/he/it: doesn't", "g", "m"],
["This is Mona. ____ is my cousin.", "دي منى. هي بنت عمي.", ["They", "She", "It", "He"], 1, "Mona بنت، يبقى She", "g", "m"],
["There ____ a lot of water in the bottle.", "في مية كتير في الإزازة.", ["are", "am", "is", "be"], 2, "water مش بيتعد، يبقى is", "g", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["It is red.", "She like apples.", "I am a student.", "We are friends."], 1, "الصح: She likes apples", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["They is happy.", "We are here.", "He is my brother.", "I am tired."], 0, "الصح: They are happy", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She goes to school.", "We go to school.", "I goes to school.", "They go to school."], 2, "الصح: I go to school", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I have a dog.", "You have a pen.", "My sister have a cat.", "We have a car."], 2, "الصح: My sister has a cat", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["Yesterday I go to the park.", "Tomorrow I will play.", "Today I am at home.", "Now I am eating."], 0, "الصح: Yesterday I went to the park", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["There is a bag.", "There is two pens.", "There are many chairs.", "There are three books."], 1, "الصح: There are two pens", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["He can run fast.", "She can sing well.", "I can swim.", "They can to play."], 3, "الصح: They can play", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I don't like tea.", "We don't have time.", "He doesn't know.", "She doesn't likes tea."], 3, "الصح: She doesn't like tea", "w", "m"],
["He is a very ____ man; he gives money to poor people.", "هو راجل كريم؛ بيدي فلوس للفقراء.", ["generous", "rude", "shy", "selfish"], 0, "generous = كريم", "v", "m"],
["I was ____ when I saw the snake, so I screamed.", "كنت خايف لما شفت التعبان فصرخت.", ["scared", "calm", "proud", "bored"], 0, "scared = خايف", "v", "m"],
["The test was very ____ ; nobody could finish it.", "الامتحان كان صعب جدًا ومحدّش عرف يخلّصه.", ["easy", "difficult", "funny", "short"], 1, "difficult = صعب", "v", "m"],
["Please ____ the door; it is cold.", "من فضلك اقفل الباب؛ الجو برد.", ["open", "break", "buy", "close"], 3, "close = يقفل", "v", "m"],
["A ____ is a person who flies a plane.", "الطيّار هو اللي بيسوق الطيارة.", ["farmer", "pilot", "waiter", "baker"], 1, "pilot = طيّار", "v", "m"],
["I need to ____ my homework before dinner.", "لازم أخلّص واجبي قبل العشا.", ["forget", "wash", "finish", "sell"], 2, "finish = يخلّص", "v", "m"],
["We ____ for the bus every morning.", "بنستنى الأتوبيس كل صباح.", ["wear", "win", "wash", "wait"], 3, "wait = يستنى", "v", "m"],
["Our teacher gives us a lot of ____ .", "المدرّس بيدّينا واجبات كتير.", ["traffic", "homework", "weather", "music"], 1, "homework = واجب", "v", "m"],
["The ____ of Egypt is Cairo.", "عاصمة مصر هي القاهرة.", ["island", "border", "desert", "capital"], 3, "capital = عاصمة", "v", "m"],
["You must ____ the road carefully.", "لازم تعدّي الشارع بحذر.", ["drop", "cross", "build", "paint"], 1, "cross = يعدّي", "v", "m"],
["It is dangerous; please be ____ .", "ده خطر؛ خلي بالك.", ["lazy", "noisy", "careless", "careful"], 3, "careful = حذر", "v", "m"],
["My grandfather is ____ ; he is eighty years old.", "جدي كبير في السن؛ عنده تمانين سنة.", ["thin", "old", "young", "new"], 1, "old = كبير في السن", "v", "m"],
["The weather is ____ ; I can see the sun.", "الجو مشمس؛ بشوف الشمس.", ["snowy", "rainy", "foggy", "sunny"], 3, "sunny = مشمس", "v", "m"],
["A ____ is a book of maps.", "الأطلس كتاب خرائط.", ["atlas", "novel", "menu", "diary"], 0, "atlas = أطلس", "v", "m"],
["We should ____ water because it is precious.", "لازم نوفّر المية لأنها غالية.", ["waste", "spill", "throw", "save"], 3, "save = يوفّر", "v", "m"],
["He is very ____ ; he never tells lies.", "هو صادق؛ عمره ما بيكدب.", ["funny", "angry", "honest", "famous"], 2, "honest = صادق", "v", "m"],
["I feel ____ today; I have a headache.", "حاسس إني تعبان النهاردة؛ عندي صداع.", ["proud", "lucky", "sick", "brave"], 2, "sick = مريض", "v", "m"],
["The ____ is the part of the body that pumps blood.", "القلب هو الجزء اللي بيضخ الدم.", ["tooth", "elbow", "knee", "heart"], 3, "heart = قلب", "v", "m"],
["The word enormous means very ____ .", "كلمة enormous معناها كبير جدًا.", ["small", "cold", "slow", "big"], 3, "enormous = ضخم", "v", "m"],
["We use a ____ to see far away objects.", "بنستخدم المنظار علشان نشوف حاجات بعيدة.", ["pillow", "telescope", "spoon", "ruler"], 1, "telescope = تلسكوب", "v", "m"],
["If it rains tomorrow, we ____ at home.", "لو الدنيا مطرت بكرة، هنفضل في البيت.", ["staying", "stayed", "will stay", "stays"], 2, "if + مضارع، وبعدها will + فعل", "g", "m"],
["She has lived here ____ 2015.", "هي عايشة هنا من سنة 2015.", ["during", "ago", "for", "since"], 3, "since مع تاريخ بداية", "g", "m"],
["We have studied English ____ three years.", "بنذاكر إنجليزي بقالنا تلات سنين.", ["ago", "for", "since", "at"], 1, "for مع المدة", "g", "m"],
["He is good ____ math.", "هو شاطر في الرياضيات.", ["in", "on", "to", "at"], 3, "good at = شاطر في", "g", "m"],
["The book ____ by many students.", "الكتاب بيتقرا من طلاب كتير.", ["read", "is reading", "reads", "is read"], 3, "المبني للمجهول: is + اسم المفعول", "g", "m"],
["This is the ____ book I have ever read.", "ده أحسن كتاب قريته.", ["best", "goodest", "good", "better"], 0, "best = الأفضل", "g", "m"],
["This exercise is ____ than the last one.", "التمرين ده أسهل من اللي فات.", ["easiest", "easier", "easy", "more easy"], 1, "الصفة اللي بتنتهي بـ y: ier", "g", "m"],
["You ____ wear a seat belt in the car.", "لازم تلبس حزام الأمان في العربية.", ["may", "would", "can", "must"], 3, "must = لازم", "g", "m"],
["You ____ smoke here; it is forbidden.", "ممنوع تدخّن هنا.", ["must", "can", "mustn't", "should"], 2, "mustn't = ممنوع", "g", "m"],
["I ____ my homework when the teacher came.", "كنت بعمل واجبي لما المدرّس جه.", ["do", "am doing", "did", "was doing"], 3, "الماضي المستمر: was + ing", "g", "m"],
["He ____ TV when the phone rang.", "كان بيتفرج على التلفزيون لما التليفون رن.", ["is watching", "watches", "was watching", "watch"], 2, "الماضي المستمر: was + ing", "g", "m"],
["There isn't ____ milk in the fridge.", "مفيش لبن في التلاجة.", ["some", "a", "any", "many"], 2, "any في النفي", "g", "m"],
["Would you like ____ juice?", "تحب عصير؟", ["some", "a", "many", "any"], 0, "some في العرض", "g", "m"],
["I enjoy ____ football.", "بستمتع بلعب الكورة.", ["to played", "play", "playing", "played"], 2, "بعد enjoy بنستخدم فعل + ing", "g", "m"],
["She wants ____ a doctor.", "هي عايزة تبقى دكتورة.", ["to be", "being", "be", "is"], 0, "بعد want بنستخدم to + فعل", "g", "m"],
["The boy ____ is sitting there is my cousin.", "الولد اللي قاعد هناك ابن عمي.", ["who", "where", "whose", "which"], 0, "who للأشخاص", "g", "m"],
["This is the pen ____ I bought yesterday.", "ده القلم اللي اشتريته امبارح.", ["where", "whose", "which", "who"], 2, "which للأشياء", "g", "m"],
["If I ____ rich, I would buy a big house.", "لو كنت غني كنت اشتريت بيت كبير.", ["were", "be", "will be", "am"], 0, "if + were في الأمنيات", "g", "m"],
["English ____ in many countries.", "الإنجليزي بيتكلّموه في بلاد كتير.", ["spoke", "is speaking", "is spoken", "speaks"], 2, "المبني للمجهول: is + اسم المفعول", "g", "m"],
["We ____ to the zoo last Friday.", "روحنا الحديقة الجمعة اللي فاتت.", ["going", "went", "go", "goes"], 1, "last Friday = ماضي", "g", "m"],
["How ____ students are there in your class?", "كام طالب في فصلك؟", ["old", "long", "much", "many"], 3, "many مع المعدود", "g", "m"],
["She is the ____ girl in our class.", "هي أطول بنت في فصلنا.", ["most tall", "tall", "taller", "tallest"], 3, "tallest = الأطول", "g", "m"],
["I have ____ finished my homework.", "أنا خلّصت واجبي خلاص.", ["tomorrow", "yet", "already", "ago"], 2, "already في الإيجاب", "g", "m"],
["Have you finished your homework ____ ?", "خلّصت واجبك ولا لسه؟", ["yet", "already", "ago", "last"], 0, "yet في السؤال", "g", "m"],
["My parents ____ TV every evening.", "أهلي بيتفرجوا على التلفزيون كل مساء.", ["watch", "watches", "is watch", "watching"], 0, "مع الجمع بنكتب الفعل من غير s", "g", "m"],
["Let's ____ to the park.", "يلا نروح الحديقة.", ["going", "went", "go", "goes"], 2, "بعد let's بنكتب الفعل من غير to", "g", "m"],
["I usually ____ up at six.", "عادةً بصحى الساعة 6.", ["gets", "get", "got", "getting"], 1, "مع I بنكتب الفعل من غير s", "g", "m"],
["Ali and Omar ____ best friends.", "علي وعمر أصحاب مقربين.", ["are", "is", "be", "am"], 0, "اتنين = are", "g", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She is taller than me.", "He is more tall than me.", "It is bigger than that.", "I am happier than him."], 1, "الصح: He is taller than me", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I have lived here since five years.", "He works hard.", "We are ready.", "I live in Cairo."], 0, "الصح: for five years", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I don't know.", "They don't play.", "She doesn't has a car.", "He doesn't like fish."], 2, "الصح: She doesn't have a car", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["We love playing.", "She likes reading.", "I enjoy to swim.", "I enjoy swimming."], 2, "الصح: I enjoy swimming", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["There is some milk.", "There are two cats.", "There are many books here.", "There are many peoples here."], 3, "الصح: many people", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She can swim.", "We must leave.", "He must goes now.", "They should study."], 2, "الصح: He must go now", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I am agree with you.", "She is happy.", "We are friends.", "I like tea."], 0, "الصح: I agree with you", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["How old are you?", "Where you live?", "Who is your teacher?", "What time is it?"], 1, "الصح: Where do you live?", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I didn't see him.", "I didn't saw him.", "She didn't go.", "We didn't eat."], 1, "الصح: I didn't see him", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["My hair is long.", "This money is mine.", "The news are good.", "The news is good."], 2, "الصح: The news is good", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She asked me to open the door.", "They hope to winning.", "I want you to stay.", "He told me to wait."], 1, "الصح: They hope to win", "w", "m"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["If it rains, I will stay home.", "If she will come, I will go.", "If I have time, I will call you.", "If he studies, he passes."], 1, "الصح: If she comes, I will go", "w", "m"],
["The sky is ____ .", "السما زرقا.", ["blue", "red", "green", "black"], 0, "blue = أزرق", "v", "p"],
["A ____ says meow.", "القطة بتقول مياو.", ["dog", "cat", "cow", "duck"], 1, "cat = قطة", "v", "p"],
["A ____ says woof.", "الكلب بيقول هاو.", ["dog", "fish", "bird", "cat"], 0, "dog = كلب", "v", "p"],
["I eat an ____ .", "باكل تفاحة.", ["pencil", "table", "apple", "chair"], 2, "apple = تفاحة", "v", "p"],
["My father's wife is my ____ .", "مرات أبويا هي أمي.", ["sister", "friend", "mother", "teacher"], 2, "mother = أم", "v", "p"],
["I write with a ____ .", "بكتب بقلم.", ["ball", "spoon", "shoe", "pencil"], 3, "pencil = قلم رصاص", "v", "p"],
["I see with my ____ .", "بشوف بعيوني.", ["ears", "eyes", "hands", "feet"], 1, "eyes = عيون", "v", "p"],
["I hear with my ____ .", "بسمع بودني.", ["eyes", "mouth", "nose", "ears"], 3, "ears = ودان", "v", "p"],
["One, two, ____ .", "واحد، اتنين، تلاتة.", ["five", "ten", "seven", "three"], 3, "three = تلاتة", "v", "p"],
["Five plus five is ____ .", "خمسة زائد خمسة يساوي عشرة.", ["four", "ten", "twelve", "six"], 1, "ten = عشرة", "v", "p"],
["A ____ is a yellow fruit.", "الموزة فاكهة صفرا.", ["banana", "potato", "carrot", "tomato"], 0, "banana = موز", "v", "p"],
["I drink ____ in the morning.", "بشرب لبن الصبح.", ["sand", "milk", "paper", "soap"], 1, "milk = لبن", "v", "p"],
["A ____ can fly.", "الطير بيطير.", ["cat", "bird", "fish", "dog"], 1, "bird = طائر", "v", "p"],
["A fish lives in ____ .", "السمكة بتعيش في المية.", ["the sky", "a house", "a tree", "water"], 3, "water = مية", "v", "p"],
["Monday, Tuesday, ____ .", "الاتنين، التلات، الأربع.", ["Friday", "Wednesday", "Sunday", "Saturday"], 1, "Wednesday = الأربع", "v", "p"],
["I go to ____ to learn.", "بروح المدرسة علشان أتعلم.", ["zoo", "school", "bed", "bank"], 1, "school = مدرسة", "v", "p"],
["It is hot. I want ice ____ .", "الجو حر. عايز آيس كريم.", ["bag", "door", "cream", "shoe"], 2, "ice cream = آيس كريم", "v", "p"],
["The opposite of hot is ____ .", "عكس حار هو بارد.", ["tall", "fast", "big", "cold"], 3, "cold = بارد", "v", "p"],
["The opposite of up is ____ .", "عكس فوق هو تحت.", ["big", "down", "in", "on"], 1, "down = تحت", "v", "p"],
["A ____ has four legs and says moo.", "البقرة ليها 4 رجلين وبتقول موو.", ["bird", "duck", "fish", "cow"], 3, "cow = بقرة", "v", "p"],
["I wear ____ on my feet.", "بلبس جزمة في رجليا.", ["glasses", "gloves", "shoes", "a hat"], 2, "shoes = جزمة", "v", "p"],
["Red, blue, green and yellow are ____ .", "أحمر وأزرق وأخضر وأصفر ألوان.", ["colors", "numbers", "animals", "fruits"], 0, "colors = ألوان", "v", "p"],
["I eat ____ with a spoon.", "باكل شوربة بالمعلقة.", ["bread", "sandwich", "soup", "apple"], 2, "soup = شوربة", "v", "p"],
["My ____ teaches me at school.", "المدرّس بيعلّمني في المدرسة.", ["baker", "teacher", "doctor", "driver"], 1, "teacher = مدرّس", "v", "p"],
["Summer is ____ and winter is cold.", "الصيف حر والشتا برد.", ["new", "hot", "dark", "short"], 1, "hot = حار", "v", "p"],
["I sleep in my ____ .", "بنام في سريري.", ["car", "school", "bed", "garden"], 2, "bed = سرير", "v", "p"],
["The ____ is round and we play with it.", "الكورة مدوّرة وبنلعب بيها.", ["door", "ball", "desk", "book"], 1, "ball = كورة", "v", "p"],
["My sister is a girl. My brother is a ____ .", "أختي بنت. أخويا ولد.", ["woman", "girl", "cat", "boy"], 3, "boy = ولد", "v", "p"],
["I ____ a boy.", "أنا ولد.", ["is", "are", "am", "be"], 2, "مع I بنستخدم am", "g", "p"],
["She ____ my friend.", "هي صاحبتي.", ["am", "is", "are", "be"], 1, "مع she بنستخدم is", "g", "p"],
["They ____ students.", "هم طلاب.", ["are", "am", "be", "is"], 0, "مع they بنستخدم are", "g", "p"],
["I have ____ orange.", "عندي برتقالة.", ["many", "two", "a", "an"], 3, "orange بتبدأ بحرف متحرك، يبقى an", "g", "p"],
["I have ____ dog.", "عندي كلب.", ["any", "are", "a", "an"], 2, "dog بتبدأ بحرف ساكن، يبقى a", "g", "p"],
["This ____ my book.", "ده كتابي.", ["are", "be", "is", "am"], 2, "مع this بنستخدم is", "g", "p"],
["These ____ my pens.", "دول أقلامي.", ["am", "are", "be", "is"], 1, "مع these (جمع) بنستخدم are", "g", "p"],
["I can ____ .", "أقدر أجري.", ["runs", "running", "runned", "run"], 3, "بعد can بنكتب الفعل زي ما هو", "g", "p"],
["One cat, two ____ .", "قطة واحدة، قطتين.", ["cates", "cats", "cat", "catt"], 1, "الجمع بنزوّد s", "g", "p"],
["This is ____ book.", "ده كتابي.", ["my", "we", "me", "I"], 0, "my = بتاعي", "g", "p"],
["He ____ a bag.", "هو معاه شنطة.", ["have", "having", "haves", "has"], 3, "مع he بنستخدم has", "g", "p"],
["We ____ happy.", "إحنا سعداء.", ["be", "are", "am", "is"], 1, "مع we بنستخدم are", "g", "p"],
["What ____ your name?", "اسمك إيه؟", ["be", "are", "am", "is"], 3, "مع name بنستخدم is", "g", "p"],
["How ____ are you?", "عندك كام سنة؟", ["old", "many", "long", "much"], 0, "How old = عمرك كام", "g", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She are my friend.", "We are happy.", "He is tall.", "I am a boy."], 0, "الصح: She is my friend", "w", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["We have a car.", "He have a ball.", "You have a pen.", "I have a cat."], 1, "الصح: He has a ball", "w", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["This is a dog.", "This is a egg.", "This is a bag.", "This is an apple."], 1, "الصح: This is an egg", "w", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She is nice.", "They is boys.", "I am happy.", "We are friends."], 1, "الصح: They are boys", "w", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I see two fish.", "I see two cat.", "I see two birds.", "I see two dogs."], 1, "الصح: I see two cats", "w", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She can run.", "He can jumps.", "I can swim.", "We can sing."], 1, "بعد can بنكتب الفعل من غير s", "w", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["My name is Ali.", "I like apples.", "I am eleven year old.", "I have a book."], 2, "الصح: I am eleven years old", "w", "p"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["The sun is hot.", "It is a red ball.", "I am a girl.", "He am a boy."], 3, "الصح: He is a boy", "w", "p"]
];
