// بنك الأسئلة: ضيف أسئلة جديدة بنفس الشكل
// [الجملة الإنجليزي, الترجمة, [الاختيارات], رقم الإجابة الصح (يبدأ من 0), الملاحظة, النوع v/g/w]
var Q=[
["It is very ____ today, so I need my coat.","الجو برد جدًا النهاردة، فمحتاج جاكتي.",["cold","hot","sunny","dry"],0,"الجاكت بنلبسه في البرد","v"],
["He is very ____ . He saved the cat.","هو شجاع جدًا. هو أنقذ القطة.",["Brave","Lazy","Hungry","Quiet"],0,"Brave = شجاع","v"],
["I am ____ because I did not eat all day.","أنا جعان لأني ماكلتش طول اليوم.",["Angry","Hungry","Late","Cold"],1,"Hungry = جعان","v"],
["We use a ____ to write on paper.","بنستخدم قلم علشان نكتب على الورق.",["pen","chair","door","bus"],0,"pen = قلم","v"],
["My mother works in a hospital. She is a ____ .","أمي بتشتغل في مستشفى. هي ممرضة.",["farmer","nurse","pilot","baker"],1,"nurse = ممرضة","v"],
["The opposite of big is ____ .","عكس كبير هو صغير.",["tall","long","small","fast"],2,"small = صغير","v"],
["I wash my hands with ____ and water.","بغسل إيديا بالصابون والمية.",["soap","bread","paper","milk"],0,"soap = صابون","v"],
["A place where we borrow books is a ____ .","المكان اللي بنستلف منه كتب هو مكتبة.",["shop","library","farm","bank"],1,"library = مكتبة","v"],
["She ____ to school every day.","هي بتروح المدرسة كل يوم.",["go","goes","going","gone"],1,"مع he/she/it بنزوّد s للفعل","g"],
["They ____ playing football now.","هم بيلعبوا كورة دلوقتي.",["is","am","are","be"],2,"مع they بنستخدم are","g"],
["I ____ breakfast yesterday at 8.","أنا فطرت امبارح الساعة 8.",["eat","eats","ate","eaten"],2,"yesterday = ماضي، وماضي eat هو ate","g"],
["There ____ two books on the desk.","في كتابين على المكتب.",["is","are","am","be"],1,"كتابين = جمع، يبقى are","g"],
["He does not ____ milk.","هو مش بيحب اللبن.",["likes","like","liking","liked"],1,"بعد does not بنكتب الفعل من غير s","g"],
["My sister is ____ than me.","أختي أطول مني.",["tall","taller","tallest","more tall"],1,"المقارنة: كلمة قصيرة + er","g"],
["We ____ to the park tomorrow.","إحنا هنروح الحديقة بكرة.",["went","goes","will go","going"],2,"tomorrow = مستقبل، نستخدم will","g"],
["This is ____ apple.","دي تفاحة.",["a","an","some","many"],1,"apple بتبدأ بحرف متحرك، يبقى an","g"],
["Which sentence is wrong?","أي جملة فيها غلط؟",["She likes pizza.","He go to school.","They are happy.","I am a student."],1,"الصح: He goes to school","w"],
["Which sentence is wrong?","أي جملة فيها غلط؟",["My father work in a bank.","She is my friend.","I like tea.","They live here."],0,"الصح: My father works in a bank","w"],
["Which sentence is wrong?","أي جملة فيها غلط؟",["There is a book.","She don't like fish.","We are late.","It is cold."],1,"الصح: She doesn't like fish","w"],
["Which sentence is wrong?","أي جملة فيها غلط؟",["I can swim.","He can swims fast.","She can run.","They can sing."],1,"بعد can بنكتب الفعل من غير s","w"],
["It is raining, so I take my ____ .", "الدنيا بتمطر، فباخد الشمسية بتاعتي.", ["pillow", "sandwich", "umbrella", "guitar"], 2, "umbrella = شمسية", "v"],
["My father drives a ____ to work.", "أبويا بيسوق عربية للشغل.", ["tree", "cloud", "spoon", "car"], 3, "car = عربية", "v"],
["I drink ____ when I am thirsty.", "بشرب مية لما أبقى عطشان.", ["sand", "water", "chalk", "paper"], 1, "thirsty = عطشان", "v"],
["Summer is very ____ in Egypt.", "الصيف حر جدًا في مصر.", ["icy", "freezing", "snowy", "hot"], 3, "hot = حار", "v"],
["A ____ is a person who teaches students.", "المدرّس هو الشخص اللي بيعلّم الطلاب.", ["driver", "doctor", "teacher", "singer"], 2, "teacher = مدرّس", "v"],
["She is ____ because she lost her toy.", "هي حزينة لأنها ضيّعت لعبتها.", ["proud", "excited", "sad", "happy"], 2, "sad = حزين", "v"],
["We sleep at night in our ____ .", "بننام بالليل في أوضة النوم.", ["garage", "balcony", "bedroom", "bathroom"], 2, "bedroom = أوضة نوم", "v"],
["The ____ gives us light and heat.", "الشمس بتدينا نور وحرارة.", ["snow", "sun", "wind", "rain"], 1, "sun = شمس", "v"],
["I am ____ ; I want to sleep.", "أنا تعبان؛ عايز أنام.", ["busy", "funny", "tired", "early"], 2, "tired = تعبان", "v"],
["A ____ lives in the sea.", "السمكة بتعيش في البحر.", ["horse", "bird", "cat", "fish"], 3, "fish = سمكة", "v"],
["The opposite of easy is ____ .", "عكس سهل هو صعب.", ["clean", "simple", "hard", "soft"], 2, "hard = صعب", "v"],
["My birthday is in ____ ; it is the first month.", "عيد ميلادي في يناير؛ هو أول شهر.", ["May", "March", "July", "January"], 3, "January = يناير", "v"],
["You can buy bread at a ____ .", "تقدر تشتري عيش من المخبز.", ["school", "bakery", "library", "hospital"], 1, "bakery = مخبز", "v"],
["I brush my ____ every morning.", "بغسل أسناني كل صباح.", ["hands", "books", "teeth", "shoes"], 2, "teeth = أسنان", "v"],
["My brother ____ football every Friday.", "أخويا بيلعب كورة كل جمعة.", ["plays", "played", "playing", "play"], 0, "مع he/she/it بنزوّد s للفعل", "g"],
["We ____ a test yesterday.", "كان عندنا اختبار امبارح.", ["have", "has", "had", "having"], 2, "yesterday = ماضي، وماضي have هو had", "g"],
["She is ____ a book now.", "هي بتقرا كتاب دلوقتي.", ["read", "readed", "reads", "reading"], 3, "now = مضارع مستمر: is + ing", "g"],
["I have ____ brothers and one sister.", "عندي أخين وأخت واحدة.", ["much", "two", "a", "an"], 1, "brothers = جمع، نستخدم رقم", "g"],
["How ____ apples are in the basket?", "كام تفاحة في السلة؟", ["a", "much", "any", "many"], 3, "apples بتتعد، يبقى many", "g"],
["How ____ milk do you drink?", "بتشرب لبن قد إيه؟", ["two", "much", "few", "many"], 1, "milk مش بيتعد، يبقى much", "g"],
["He ____ his homework yesterday.", "هو عمل واجبه امبارح.", ["do", "did", "does", "doing"], 1, "yesterday = ماضي، وماضي do هو did", "g"],
["Ahmed and Sara ____ my friends.", "أحمد وسارة أصحابي.", ["am", "is", "be", "are"], 3, "اتنين = are", "g"],
["I get up ____ 7 o'clock.", "بصحى الساعة 7.", ["of", "at", "on", "in"], 1, "قبل الساعة بنستخدم at", "g"],
["My birthday is ____ May.", "عيد ميلادي في مايو.", ["in", "at", "to", "on"], 0, "قبل الشهر بنستخدم in", "g"],
["This book is ____ than that one.", "الكتاب ده أمتع من اللي ده.", ["most interesting", "interesting", "more interesting", "interestinger"], 2, "الكلمة الطويلة: more + الصفة", "g"],
["They ____ at home last night.", "هم كانوا في البيت الليلة اللي فاتت.", ["were", "are", "was", "is"], 0, "they + الماضي = were", "g"],
["I ____ my friend tomorrow.", "هقابل صاحبي بكرة.", ["will meet", "met", "meeting", "meets"], 0, "tomorrow = مستقبل: will + فعل", "g"],
["She can ____ English very well.", "هي تقدر تتكلم إنجليزي كويس جدًا.", ["speaks", "speak", "speaking", "spoke"], 1, "بعد can بنكتب الفعل من غير s", "g"],
["____ you like pizza?", "بتحب البيتزا؟", ["Is", "Does", "Are", "Do"], 3, "مع you بنستخدم Do", "g"],
["My mother ____ cook every day.", "أمي مش بتطبخ كل يوم.", ["doesn't", "don't", "isn't", "aren't"], 0, "مع she/he/it: doesn't", "g"],
["This is Mona. ____ is my cousin.", "دي منى. هي بنت عمي.", ["They", "She", "It", "He"], 1, "Mona بنت، يبقى She", "g"],
["There ____ a lot of water in the bottle.", "في مية كتير في الإزازة.", ["are", "am", "is", "be"], 2, "water مش بيتعد، يبقى is", "g"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["It is red.", "She like apples.", "I am a student.", "We are friends."], 1, "الصح: She likes apples", "w"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["They is happy.", "We are here.", "He is my brother.", "I am tired."], 0, "الصح: They are happy", "w"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["She goes to school.", "We go to school.", "I goes to school.", "They go to school."], 2, "الصح: I go to school", "w"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I have a dog.", "You have a pen.", "My sister have a cat.", "We have a car."], 2, "الصح: My sister has a cat", "w"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["Yesterday I go to the park.", "Tomorrow I will play.", "Today I am at home.", "Now I am eating."], 0, "الصح: Yesterday I went to the park", "w"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["There is a bag.", "There is two pens.", "There are many chairs.", "There are three books."], 1, "الصح: There are two pens", "w"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["He can run fast.", "She can sing well.", "I can swim.", "They can to play."], 3, "الصح: They can play", "w"],
["Which sentence is wrong?", "أي جملة فيها غلط؟", ["I don't like tea.", "We don't have time.", "He doesn't know.", "She doesn't likes tea."], 3, "الصح: She doesn't like tea", "w"]
];
